return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local config = require("nvim-treesitter.configs")
        config.setup({
            ensure_installed = {
                "awk",
                "bash",
                "c",
                "cmake",
                "cpp",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "editorconfig",
                "gitignore",
                "go",
                "gomod",
                "gosum", 
                "graphql",
                "http",
                "ini",
                "javascript",
                "json",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "nginx",
                "perl",
                "php",
                "python",
                "rst",
                "ruby",
                "rust",
                "scss",
                "sql",
                "ssh_config",
                "tmux",
                "toml",
                "tsx",
                "twig",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "wgsl",
                "xml",
                "yaml",
            },
            auto_install = true,
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end
}

